#!/bin/bash

# Ofboarding client serverside actions.
# CA-Variables
export CADIR=/usr/share/fd-vertel-se/
export SLAPDPRIVKEY=/etc/ldap/fd_vertel_se_slapd_key.pem
export CACERT=/etc/ssl/certs/mycacert.pem
export CAPRIVKEY=/etc/ssl/private/mycakey.pem


# Certificate for an OpenLDAP replica  (consumer/client)

export CLIENT=$1
export CLIENTDIR="$CLIENT"-ssl
export CLIENT_PRIVKEY="$CLIENT"_slapd_key.pem
export CLIENT_CERT="$CLIENT"_slapd_cert.pem
# Check $CLIENT
echo CLIENT = $CLIENT
echo CLIENTDIR = $CLIENTDIR
if [ -z "$CLIENT" ]
then
  echo "Missing name of client parameter: $0 [client]"
  exit
fi
cd $CADIR
# Check $CLIENTDIR
if ! [ -d "$CLIENTDIR" ]
then
  echo "Missing directory $CLIENTDIR of client parameter: $0 [client]"
  exit
fi

echo "Remove directory and files for $CLIENT"
# Check directory: (exists + rights)
cd $CLIENTDIR
# Go there...!

echo Touch ... This path... = `pwd`

sudo touch delete-certinfo.ldif
sudo chmod a+w delete-certinfo.ldif
# Create the file delete-certinfo.ldif
echo """dn: cn=config
delete: olcTLSCertificateFile
olcTLSCertificateFile: /etc/ldap/$CLIENT_PRIVKEY
-
delete: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /etc/ldap/$CLIENT_CERT""" > delete-certinfo.ldif

sudo ldapmodify -Y EXTERNAL -H ldapi:/// -f delete-certinfo.ldif

cd ..
sudo rm -rf $CLIENTDIR


#### DONE
echo DONE
