#!/bin/bash

# Ofboarding client serverside actions.
# CA-Variables
export CADIR=/usr/share/fd-vertel-se/
export SLAPDPRIVKEY=/etc/ldap/fd_vertel_se_slapd_key.pem
export CACERT=/etc/ssl/certs/mycacert.pem
export CAPRIVKEY=/etc/ssl/private/mycakey.pem


# Certificate for an OpenLDAP replica  (consumer/client)

export CLIENT=$1
export CLIENTDIR="$CLIENT"-ssl
export CLIENT_PRIVKEY="$CLIENT"_slapd_key.pem
export CLIENT_CERT="$CLIENT"_slapd_cert.pem
# Check $CLIENT
if [ -z "$CLIENT" ]
then
  echo "Missing name of client parameter: wget .... | bash -s [client]"
  exit
fi

echo "Create directory and files for $CLIENT"

# Check directory: (exists + rights)
cd $CADIR
sudo rm -rf $CLIENTDIR
mkdir $CLIENTDIR
cd $CLIENTDIR

# Go there...!

# Create the file delete-certinfo.ldif
echo """dn: cn=config
delete: olcTLSCACertificateFile
olcTLSCACertificateFile: /etc/ssl/certs/mycacert.pem
-
delete: olcTLSCertificateFile
olcTLSCertificateFile: /etc/ldap/$CLIENT_PRIVKEY
-
delete: olcTLSCertificateKeyFile
olcTLSCertificateKeyFile: /etc/ldap/$CLIENT_CERT""" > certinfo.ldif

sudo ldapmodify -Y EXTERNAL -H ldapi:/// -f delete-certinfo.ldif

# Create info file
echo """organization = Vertel AB
cn = $CLIENT.vertel.se
tls_www_server
encryption_key
signing_key
expiration_days = 3650
""" > $CLIENT.info

# Create the consumer/client certificate

sudo certtool --generate-certificate \
--load-privkey $CLIENT_PRIVKEY \
--load-ca-certificate $CACERT \
--load-ca-privkey $CAPRIVKEY \
--template $CLIENT.info \
--outfile $CLIENT_CERT

# Get a copy of the CA certificate:
cp $CACERT .




#### DONE
echo DONE
